# Generated by Django 4.2.6 on 2023-10-09 13:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='interactions',
            managers=[
                ('managers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='interactions',
            name='meeting',
            field=models.DateField(),
        ),
    ]
