# Generated by Django 4.2.6 on 2023-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_interactions_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='meeting',
            field=models.DateTimeField(),
        ),
    ]
