# Generated by Django 4.2.6 on 2023-10-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_interactions_meeting'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tasks',
            managers=[
            ],
        ),
    ]
