# Generated by Django 4.2.6 on 2023-10-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_tasks_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
