# Generated by Django 4.2.6 on 2023-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(choices=[('STATES', 'STATES'), ('MOTORCYCLE', 'MOTORCYCLE')], max_length=30, null=True)),
                ('note', models.TextField(default='Max length is 2500 words', max_length=2500)),
            ],
        ),
    ]
